### ISSUE TITLE
partial template

### ISSUE THREAD

**Issue by seb-jean** [VincentLanglet/Twig-CS-Fixer#198] opened 2024-02-24 20:48 UTC
### Rule(s) related to or rule(s) missing

`FileNameRule`

### Expected behavior

Sometimes we use partial templates. For example for the Symfony demo, there is the file https://github.com/symfony/demo/blob/main/templates/blog/_post.html.twig

I then tested and I got the error below:

### Actual behavior

```
 KO .\templates\blog\_post.html.twig
 ------- ----------------------------------------------------------
  ERROR   >>   | The file name must use snake_case; expected post.
```

Do you think this behavior should be taken into account?

**Comment by VincentLanglet** [comment] 2024-02-24 21:36
> Do you think this behavior should be taken into account?

Yes, it should be indeed.

**Comment by VincentLanglet** [comment] 2024-02-24 21:57
Does https://github.com/VincentLanglet/Twig-CS-Fixer/pull/199 would solve your issue @seb-jean ?

**Comment by seb-jean** [comment] 2024-02-25 10:00
It's better :).

However, when I have a file like this: `tailwind_2_layout.html.twig`, I get the error below:
```
  KO .\templates\form\tailwind_2_layout.html.twig
  ------- -------------------------------------------- ---------------------------
   ERROR >> | The file name must use snake_case; expected tailwind2_layout.
```

**Comment by VincentLanglet** [comment] 2024-02-25 10:52
> However, when I have a file like this: `tailwind_2_layout.html.twig`, I get the error below:
> 
> ```
>   KO .\templates\form\tailwind_2_layout.html.twig
>   ------- -------------------------------------------- ---------------------------
>    ERROR >> | The file name must use snake_case; expected tailwind2_layout.
> ```

I rely on Symfony/string for the case validator.
I check if you string is the same than the one produced by this method
https://github.com/symfony/string/blob/7.0/AbstractUnicodeString.php#L347-L353

And looking at the tests it seems to be an expected behavior https://github.com/symfony/string/blob/7.0/Tests/AbstractAsciiTestCase.php#L1063-L1077

When looking on the net, there is some discussion about should it be `name1` or `name_1` with maybe a majority of `name1`. Anyway, I think that if you consider `name_1` should be allowed, the discussion would be on Symfony side I think.
And looking at https://github.com/symfony/symfony/issues/34777 and https://github.com/symfony/symfony/pull/34781 it seems like the discussion was already done.

So if you want to really follow the symfony standard, seems like `tailwind2_layout` is the valid way.

**Comment by seb-jean** [comment] 2024-02-25 12:03
However this file exists in Symfony:
https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Resources/views/Form/tailwind_2_layout.html.twig

**Comment by VincentLanglet** [comment] 2024-02-25 12:43
> However this file exists in Symfony: [symfony/symfony@`7.1`/src/Symfony/Bridge/Twig/Resources/views/Form/tailwind_2_layout.html.twig](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Bridge/Twig/Resources/views/Form/tailwind_2_layout.html.twig?rgh-link-date=2024-02-25T12%3A03%3A06Z)

Indeed. I opened an issue on Symfony side https://github.com/symfony/symfony/issues/54051 to know if
- The fix should be on the templates name
- The fix should be on the symfony naming standard
- The fix should be on my side

**Comment by VincentLanglet** [comment] 2024-03-22 09:22
I'll close this @seb-jean, I consider:
- The initial topic is solved
- Symfony doesn't respect their own standard for the `tailwind_2_layout.html.twig` template
- You can ignore a rule for a single file if needed https://github.com/VincentLanglet/Twig-CS-Fixer/blob/main/docs/identifiers.md

**Closed by VincentLanglet** 2024-03-22 09:22 UTC
